---
- hosts: lucentd
  gather_facts: no
  roles:
    - ubuntu-16-04

  vars:
    - x_user: lucent
    - x_group: lucent
    - x_home: /home/lucent
    - x_config_dir: /home/lucent/.lucentcore
    - x_download_url: https://github.com/LucentCoin/Lucent/releases/download/v0.12.3.3/lucent-linux.zip
    - x_download_dest: /home/ubuntu/lucent.tar.gz
    - x_download_checksum: sha1:3c5b095c3553342549d269cfb9393fdbfd579b83
    - x_unarchive_dest: /home/lucent/app

  tasks:
    - name: Install add-apt-repostory
      become: yes
      apt:
        name: software-properties-common
        state: latest

    - name: Add Bitcoin Repository
      become: yes
      apt_repository:
        repo: ppa:bitcoin/bitcoin
        state: present

    - name: Install dependencies
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - curl
        - libboost-all-dev
        - libdb4.8-dev
        - libdb4.8++-dev
        - libminiupnpc-dev
        - libzmq3-dev
        - libevent-pthreads-2.0-5

    - name: Create the lucent group
      become: yes
      group:
        name={{ x_group }}
        state=present

    - name: Create the lucent user
      become: yes
      user:
        name={{ x_user }}
        group={{ x_group }}
        state=present
        system=yes

    - name: Create the app directory
      become: yes
      file:
        path={{ x_home }}/app
        state=directory
        owner={{ x_user }}
        group={{ x_group }}

    - name: Create the config directory
      become: yes
      file:
        path={{ x_config_dir }}
        state=directory
        owner={{ x_user }}
        group={{ x_group }}

    - name: Download the lucentd
      get_url:
        url={{ x_download_url }}
        dest={{ x_download_dest }}
        checksum={{ x_download_checksum }}

    - name: Unpack the application
      become: yes
      unarchive:
        remote_src=yes
        src={{ x_download_dest }}
        dest={{ x_unarchive_dest }}
        owner={{ x_user }}
        group={{ x_group }}

    # - name: Move the application to the right folder
    #   become: yes
    #   command: mv {{ x_unarchive_dest }}/lucent-linux/lucentd {{ x_unarchive_dest }}

    - name: Set the application as executable
      become: yes
      file:
        path: "{{ x_unarchive_dest }}/lucentd"
        mode: "u=rwx"

    - name: Set the application config
      become: yes
      copy:
        src=config/lucent.conf
        dest={{ x_config_dir }}/lucent.conf
        owner={{ x_user }}
        group={{ x_group }}

    - name: Set the application files permissions
      become: yes
      file:
        dest={{ x_config_dir }}
        owner={{ x_user }}
        group={{ x_group }}
        recurse=yes

    - name: Set the application files permissions
      become: yes
      file:
        dest={{ x_unarchive_dest }}
        owner={{ x_user }}
        group={{ x_group }}
        recurse=yes

    - name: Add the systemd service
      become: yes
      copy:
        src: systemd-services/lucentd.service
        dest: /etc/systemd/system/
        owner: root
        group: root

    - name: Pick up systemd changes
      become: yes
      systemd:
        daemon_reload: yes

    - name: Restart the application
      become: yes
      systemd:
        name: lucentd
        state: restarted

    - name: Enable the application to run on system startup
      become: yes
      systemd:
        name: lucentd
        enabled: yes
